language: php
php:
- 7.1
- nightly

script:
- phpunit --coverage-clover=coverage.xml --log-junit=test-report.xml

before_install:
- composer install
- pip install --user codecov

after_success:
- codecov